# author: aa4461

# this is final.raw generated by our rerun_with_meld.sh 
# script (dumped in v2/exp/xvector_nnet_1a/final.raw)
BASE_REFERENCE_MODEL="emotion_discriminator.raw"
MODIFIED_REFERENCE_MODEL="emotion_autoencoder.raw"

BASE_DIR="nnet-emotion/conversion"
INPUT_DIR="$BASE_DIR/inputs"
OUTPUT_DIR="$BASE_DIR/outputs"
MODEL_INPUT_DIR="$INPUT_DIR/reference"
MODEL_OUTPUT_DIR="$OUTPUT_DIR/reference"
DATA_INPUT_DIR="$INPUT_DIR/data"
DATA_OUTPUT_DIR="$OUTPUT_DIR/data"
