# author: aa4461

BASE_DIR="nnet-emotion/cremad"
INPUT_DIR="$BASE_DIR/inputs"
OUTPUT_DIR="$BASE_DIR/outputs"
MODEL_INPUT_DIR="$INPUT_DIR/reference"
MODEL_OUTPUT_DIR="$OUTPUT_DIR/reference"
DATA_INPUT_DIR="corpora/CREMA-D/"
DATA_OUTPUT_DIR="$OUTPUT_DIR/data"
DATA_OUTPUT_COMBINED_DIR="$DATA_OUTPUT_DIR/all_cremad"