# this is final.raw generated by the original vox2 
# script (in v2/exp/xvector_nnet_1a/final.raw)
BASE_REFERENCE_MODEL="vox2_base.raw"
MODIFIED_REFERENCE_MODEL="vox2_modified_base.raw"

MUSAN_DIR="corpora/musan"
NOISE_DIR="corpora/RIRS_NOISES"