# author: aa4461

BASE_DIR="nnet-emotion/meld"
INPUT_DIR="$BASE_DIR/inputs"
OUTPUT_DIR="$BASE_DIR/outputs"
MODEL_INPUT_DIR="$INPUT_DIR/reference"
MODEL_OUTPUT_DIR="$OUTPUT_DIR/reference"
DATA_INPUT_DIR="corpora/MELD.Raw"
DATA_OUTPUT_DIR="$OUTPUT_DIR/data"
DATA_OUTPUT_TRAIN_DIR="$DATA_OUTPUT_DIR/train"
DATA_OUTPUT_DEV_DIR="$DATA_OUTPUT_DIR/dev"
DATA_OUTPUT_TEST_DIR="$DATA_OUTPUT_DIR/test"
DATA_OUTPUT_COMBINED_DIR="$DATA_OUTPUT_DIR/all_meld"